server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coc_event
    username: root
    password: lyj112233
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    elasticsearch:
      cluster-name: elasticsearch-docker
      cluster-nodes: 192.168.233.128:9300
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.example.elasticsearch.domain
  mapperLocations: classpath:/mapper/*.xml
